name: 'Terraform GitHub Action'
description: 'Runs terraform init, plan, and apply to the terraform directory passed'
inputs:
  terraform_dir_path:
    description: 'Directory of the terraform configuration files'
    required: true
  destroy:
    description: 'Type true to destroy already made resources'
runs:
  using: 'node16'
  main: 'dist/index.js'
